services:
  - type: web
    name: amazon-ebay-reliable-scan
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_streamlit.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
